apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metadata-collector.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metadata-collector.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "metadata-collector.config" . | nindent 4 }}
