{{- if and .Values.fileSD.enabled .Values.fileSD.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vmagent-central.fullname" . }}-file-sd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vmagent-central.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.fileSD.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
