global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "mock-dcgm"
    static_configs:
      - targets:
          - "mock-dcgm-exporter:9400"
        labels:
          deployment_env: macbook
          platform: docker
          cluster: macbook
          workload_type: training
