apiVersion: v1
kind: Service
metadata:
  name: {{ include "mock-dcgm-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mock-dcgm-exporter.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "mock-dcgm-exporter.selectorLabels" . | nindent 4 }}
